### ISSUE TITLE
package tries to install all tf-nightly versions for each and everyday for this year!

### ISSUE THREAD

**Issue by cagdemir** [google/uncertainty-baselines#336] opened 2021-05-03 13:44 UTC
I want to do some experiments on the project so I'm trying to install the package into a virtual environment. 

It tries to install tf-nightly builds for each and every day this year (like 100 versions of the same package). Given that each nightly build for tf is around 450mb this quickly eats up my limited storage and only after it fills that 50gb, it stops downloading tf nightly builds and finishes up the installation that github package. 

![tf_nightly_issue](https://user-images.githubusercontent.com/54540791/116883896-651bfd80-ac26-11eb-988a-8e83e9597af5.png)

**Comment by Jordy-VL** [comment] 2021-05-06 15:39
I have the same issue! The command I used: 

```pip install "git+https://github.com/google/uncertainty-baselines.git#egg=uncertainty_baselines[models]" ```

Collecting tf-nightly
  Downloading tf_nightly-2.6.0.dev20210505-cp38-cp38-manylinux2010_x86_64.whl (453.0 MB)
     |████████████████████████████████| 453.0 MB 7.6 kB/s 
  Downloading tf_nightly-2.6.0.dev20210504-cp38-cp38-manylinux2010_x86_64.whl (453.0 MB)
     |████████████████████████████████| 453.0 MB 42 kB/s 
  Downloading tf_nightly-2.6.0.dev20210503-cp38-cp38-manylinux2010_x86_64.whl (456.9 MB)
     |████████████████████████████████| 456.9 MB 40 kB/s 
  Downloading tf_nightly-2.6.0.dev20210502-cp38-cp38-manylinux2010_x86_64.whl (456.9 MB)
     |████████████████████████████████| 456.9 MB 45.0 MB/s 
  Downloading tf_nightly-2.6.0.dev20210501-cp38-cp38-manylinux2010_x86_64.whl (456.9 MB)
     |████████████████████████████████| 456.9 MB 49 bytes/s 
  Downloading tf_nightly-2.6.0.dev20210430-cp38-cp38-manylinux2010_x86_64.whl (456.9 MB)
     |████████████████████████████████| 456.9 MB 30.2 MB/s 
  Downloading tf_nightly-2.6.0.dev20210429-cp38-cp38-manylinux2010_x86_64.whl (456.8 MB)
     |████████████████████▏           | 287.8 MB 29.4 MB/s eta 0:00:06^C
ERROR: Operation cancelled by user

**Comment by cagdemir** [comment] 2021-05-06 18:52
I tried to use conda and never ending installation tf nightly builds stopped. But a new one emerged. The exact steps I followed are:

1. create a new environment with conda
2. activate it and install pip and git using conda
3. install uncertainty-baselines using pip (after activating new conda environment)
4. installation of uncertainty_baselines didn't handled required packages so I installed unceetainty-metrics, edward2, and tensorflow-addons explicitly using pip and conda
5. After that the error I got is 

Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0

6. After a quick internet search, found out that some people overcame the issue by installing tf-gpu, so I installed:

>conda install tensorflow-gpu cudatoolkit=10.1

7. After this importing uncertainty-baselines outputted this issue:

ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization'


I tried different things along the way but no help. I think **google needs a better package maintenance if the team wants to make this package public and their research re-producible!**

**Comment by Jordy-VL** [comment] 2021-05-06 19:46
@cagdemir  I tried similar things! 
 
What worked for me to solve the latter issue is to install tensorflow 2.4.1, followed by tf-nightly, since there LayerNormalization is properly referenced. 

I still cannot run sngp.py properly, I am afraid there is too little documentation on which exact FLAGS to run...

**Comment by dustinvtran** [comment] 2021-05-10 19:00
Thanks for raising this! That is a really strange behavior..

Does this issue also pop up if you install `tf-nightly` by itself? What about `tf-models-nightly`?

> @Jordy-VL: I still cannot run sngp.py properly, I am afraid there is too little documentation on which exact FLAGS to run...

The default flags work to exactly reproduce the table results. To help with this, I also added a bit more guidance to the README.md (see the "Launching with TPUs." section).

**Comment by znado** [comment] 2021-05-10 20:21
IIUC this was due to some bizarre pip dependency resolution, I believe it should be fixed at head now (I believe removing the `gast` dep from [setup.py](https://github.com/google/uncertainty-baselines/blob/master/setup.py) fixed it).

**Closed** 2021-05-10 20:21 UTC

**Comment by Jordy-VL** [comment] 2021-05-11 07:41
Hi @znado, 

Thanks, that did the trick. I used the command as above with [models] in a fresh environment. 
However, when I run any of the baselines, I get an ImportError from  robustness_metrics: 

```    Traceback (most recent call last):
  File "sngp.py", line 41, in <module>
    import robustness_metrics as rm
  File "/home/jordy/.virtualenvs/test/lib/python3.6/site-packages/robustness_metrics/__init__.py", line 20, in <module>
    from robustness_metrics import metrics
  File "/home/jordy/.virtualenvs/test/lib/python3.6/site-packages/robustness_metrics/metrics/__init__.py", line 40, in <module>
    from robustness_metrics.metrics import serialization
ImportError: cannot import name 'serialization'
```
Probably something to check to ensure a stable build.
